VACATION_CREATED_STATUS = 'created'
VACATION_CONFIRMED_STATUS = 'confirmed'
VACATION_ON_VACATION_STATUS = 'on_vacation'
VACATION_FINISHED_STATUS = 'finished'
VACATION_CANCELLED_STATUS = 'cancelled'

WATCH_MEMBER_OFFLINE = 'offline'
WATCH_MEMBER_ONLINE = 'online'
WATCH_MEMBER_BUSY = 'offline'

VACATION_ALL_STATUSES = [
    VACATION_CREATED_STATUS,
    VACATION_CONFIRMED_STATUS,
    VACATION_ON_VACATION_STATUS,
    VACATION_FINISHED_STATUS,
    VACATION_CANCELLED_STATUS,
]

VACATION_CREATED_DEFAULT = {
    'name': 'Создано',
    'is_booked': True,
    'sort': 100,
}
