TRAINING_CREATED_STATUS = 'created'
TRAINING_CONFIRMED_STATUS = 'confirmed'
TRAINING_ON_TRAINING_STATUS = 'on_break'
TRAINING_FINISHED_STATUS = 'finished'
TRAINING_CANCELLED_STATUS = 'cancelled'

COURT_MEMBER_OFFLINE = 'offline'
COURT_MEMBER_ONLINE = 'offline'
COURT_MEMBER_BUSY = 'offline'

TRAINING_ALL_STATUSES = [
    TRAINING_CREATED_STATUS,
    TRAINING_CONFIRMED_STATUS,
    TRAINING_ON_TRAINING_STATUS,
    TRAINING_FINISHED_STATUS,
    TRAINING_CANCELLED_STATUS,
]

TRAINING_CREATED_DEFAULT = {
    'name': 'Создано',
    'is_booked': True,
    'sort': 100,
}
